services:
  - type: web
    name: pixulse-cloud
    runtime: python-3.12
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 ak.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
