services:
  - type: web
    name: pixulse-cloud
    runtime: python-3.12
    buildCommand: "cd ak && pip install -r requirements.txt && cd .."
    startCommand: "gunicorn -w 2 -b 0.0.0.0:10000 ak.wsgi:application --chdir=ak"
